### ISSUE TITLE
色碼轉換似乎出問題了

### ISSUE THREAD

**Issue by forestluch** [Wilson403/Html2UnityRich#1]
轉換出的顏色標籤包含
<color=#FF660>
顏色轉換似乎出問題?

**Comment by Wilson403** [comment]
> 轉換出的顏色標籤包含
> <color=#FF660>
> 顏色轉換似乎出問題?

我晚点看看

**Comment by Wilson403** [comment]
> 轉換出的顏色標籤包含 <color=#FF660> 顏色轉換似乎出問題?

你是直接使用演示案例吗，我这边运行并没有发现颜色异常的地方，如果是颜色转化为十六进制后的问题，你能提供我下rgb值吗

**Comment by forestluch** [comment]
可以幫我看看這個 感謝

原本的HTML
<p class="ql-align-center"><strong style="color: rgb(255, 102, 0);">新一代「鋰離子充電電池」 與一般充電電池相比，</strong></p>

轉換後的HTML
<color=#FF660><b>新一代「鋰離子充電電池」 與一般充電電池相比，</b></color>

大部分的顏色都能轉換正常
但有少數會轉出5碼錯誤的顏色

**Comment by forestluch** [comment]
可以幫我看看這個 感謝

原本的HTML

`<p class="ql-align-center"><strong style="color: rgb(255, 102, 0);">新一代「鋰離子充電電池」 與一般充電電池相比，</strong></p>`

轉換後的HTML
`<color=#FF660><b>新一代「鋰離子充電電池」 與一般充電電池相比，</b></color>`

大部分的顏色都能轉換正常
但有少數會轉出5碼錯誤的顏色

**Comment by Wilson403** [comment]
> 可以幫我看看這個 感謝
> 
> 原本的HTML
> 
> `<p class="ql-align-center"><strong style="color: rgb(255, 102, 0);">新一代「鋰離子充電電池」 與一般充電電池相比，\</strong\></p>`
> 
> 轉換後的HTML `<color=#FF660><b>新一代「鋰離子充電電池」 與一般充電電池相比，</b></color>`
> 
> 大部分的顏色都能轉換正常 但有少數會轉出5碼錯誤的顏色

已修复，感谢你的反馈
