### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by shinefield** [Wilson403/Html2UnityRich#2]
一般html页面是个完整的，比如：
<html>
<head>标题头</head>
<body>
内容
</body>
</html>

但是这个插件会把head里面的内容也输出来，然后h1默认是块级元素，理应占一行，发现这个插件应该是用p标签进行分段的

**Comment by Wilson403** [comment]
我晚点看看这个问题

**Comment by Wilson403** [comment]
> 一般html页面是个完整的，比如：
> 
> 标题头 内容
> 但是这个插件会把head里面的内容也输出来，然后h1默认是块级元素，理应占一行，发现这个插件应该是用p标签进行分段的

我晚点看看这个问题

**Comment by Wilson403** [comment]
> 一般html页面是个完整的，比如：
> 
> 标题头 内容
> 但是这个插件会把head里面的内容也输出来，然后h1默认是块级元素，理应占一行，发现这个插件应该是用p标签进行分段的

已经处理了Head标签的问题，现在直接忽略了Head标签作用域里的内容，你更新试试
至于第二个问题“h1默认是块级元素，理应占一行”，我没有直接改提交，我可以跟你说改哪里，HtmlTagNode.cs的ToUguiRichText方法，这里会对标签含义进行解析，你可以修改试试
